# Data Structures and Algorithms in Python

### Data Structures used in Algorithms

Algorithms need necessary in-memory data structures that can hold temporary data while executing. Choosing the right data structures is essential for their efficient implementation. Certain classes of algorithms are recursive or iterative in logic and need data structures that are specially designed for them. 

### Exploring data structures in Python

In python, there are five various data structures that can be used to store collections:
    - Lists: Ordered mutable sequences of elements
    - Tuples: Ordered immutable sequences of elements
    - Sets: Unordered bags of elements
    - Dictionary: Unordered bags of key-value pairs
    - Data frames: Two-dimensional structures to store two-dimensional data

The time complexity of lists

| Different methods	| Time complexity |
| ----------------- | --------------- |
| Insert an element	|O(1) |
| Delete an element	| O(n) (as in the worst case may have to iterate the whole list) |
| Slicing a list	| O(n) |
| Element retrieval | O(n) | 
| Copy	| O(n) |

The time complexity of tuples
| Function | Time Complexity |
| -------- | --------------- |
| Append   | O(1)            |

The time complexity of dictionary
| Dictionary  | Time complexity |
| ----------- | --------------- |
| Get a value or a key |	O(1) |
| Set a value or a key |	O(1) |
| Copy a dictionary |	O(n)|

The time complexity of sets
| Sets |	Complexity |
| ---- | ------------- |
| Add an element |	O(1) |
| Remove an element |	O(1) |
| Copy	| O(n) |



### Terminologies of DataFrames
* Axis: In the pandas documentation, a single column or row of a DataFrame is called an Axis.
* Axes: If there is more than one axis, they are called axes as a group.
* Label: A DataFrame allows the naming of both columns and rows with what's called a label.

### Creating a subset of a DataFrame
* Column selection
    df[['name', 'age']]
    df.iloc[:, 3]
* Row selection
    df.iloc[1:3, :]

```
    df[df.age>30]
    df[(df.age<35)&(df.decision==True)]
```


In [5]:
# DataFrames
import pandas as pd
df = pd.DataFrame([
    ['1', 'Flares', 32, True],
    ['2', 'Elena', 33, True]
], columns = ['id', 'name', 'age', 'decision'])
print(df)

  id    name  age  decision
0  1  Flares   32      True
1  2   Elena   33      True


### Matrix
A matrix is a two-dimensional data structure with a fixed number of columns and rown. Each element of a matrix can be referred to by its column and the row. 
In Python, a matrix can be created by using the numpy array, as shown the following code.

In [7]:
# matrix
import numpy as np
my_matrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(my_matrix)
print(my_matrix.transpose())

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Abstract Data types
1. Vector
2. Stacks
3. Queues
5. Trees

**Vector**
A vector is a single dimensional structure to store data. They are one of the most popular data structures in Python. There are two ways of creating vectors in Python as follows:
a. Using a python list: 
    my_vector = [22, 33, 44, 55]

b. Using a numpy array:
    my_vector = np.array([22, 33, 44, 55])

**Stacks**
A stack is a linear data structure to store a one-dimensional list. It can store items either in LIFO, FILO, 
Following are the operations related to stacks:
    * is_empty: returns true if the stack is empty
    * push: adds a new element
    * pop: returns the element added most recently and removes it
    

In [13]:
# stacks
class Stack:
    def __init__(self):
        self.items = []
        
    def is_empty(self):
        return self.items == []
    
    def push(self, item):
        self.items.append(item)
        
    def pop(self):
        return self.items.pop()
        
    def peek(self):
        return self.items[len(self.items)-1]
    
    def size(self):
        return len(self.items)
    
stack = Stack()
stack.push("Red")
stack.push("Green")
stack.push("Blue")
print(stack.pop())
stack.is_empty()

Blue


False

**Queues**
